  services:
    db:
      image: postgres:13-alpine
      restart: always
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: 123456
      ports:
        - '5432:5432'
      healthcheck:
        test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
        interval: 10s
        timeout: 5s
        retries: 5
      volumes:
        - postgres-data:/var/lib/postgresql/data
    backend:
      build: ./project
      restart: always
      ports:
        - '8081:8081'
      environment:
          - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
          - SPRING_DATASOURCE_USERNAME=admin
          - SPRING_DATASOURCE_PASSWORD=123456
      depends_on:
        db:
          condition: service_healthy
    frontend:
      build: ./front
      restart: always
      ports:
         - '8080:80'
      depends_on:
        db:
          condition: service_healthy
        backend:
          condition: service_started
  volumes:
    postgres-data:
