INSERT INTO speciality(name, code) VALUES
('FACULTY OF ENGINEERING AND NATURAL SCIENCES', '01'),
('FACULTY OF EDUCATION AND HUMANITIES', '02'),
('FACULTY OF LAW AND SOCIAL SCIENCES', '03'),
('SCHOOL OF BUSINESS', '04');